spring:
  application:
    name: MyRest
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
server:
  servlet:
    context-path: /api
min:
  registration:
    age: 18
